# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='key',
            field=models.CharField(db_index=True, default=groups.models.generate_key, max_length=15),
        ),
    ]
