# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 14:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField()),
                ('time', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('show_task', models.BooleanField(default=False)),
                ('random_variant', models.BooleanField(default=False)),
                ('variants_count', models.PositiveSmallIntegerField(default=0)),
                ('task_type', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
            ],
        ),
    ]
