# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subject_id',
        ),
    ]
