# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 14:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField()),
                ('rate', models.CharField(default=-1, max_length=15)),
                ('first_complete', models.BooleanField(default=False)),
                ('task_type', models.PositiveSmallIntegerField(default=0)),
                ('variant', models.PositiveSmallIntegerField(default=0)),
                ('time', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
